Hw
aalyando/code pull request #2
Opened 2023-09-10 19:26 UTC by aalyando

2023-09-11 07:34 UTC, shorodilov requested changes
Потрібно внести правки

2023-09-11 07:34 UTC, shorodilov commented on hw.py
> +    return origin == origin[::-1]
Це не буде працювати для кожного з випадків.
От ще декілька тестів:
```python
assert is_palindrome("Hannah") is True
assert is_palindrome("Do geese see God?") is True
```

2023-09-13 20:23 UTC, aalyando commented on hw.py
> +    return origin == origin[::-1]
Оказалась какая-то каша с файлам, и тот на который ты ответил я не могу закомитить, получилось добавить отдельно под названием "Try2". Надеюсь, это не будет большой проблемой

2023-09-20 17:08 UTC, shorodilov approved these changes

2023-09-25 16:29 UTC, shorodilov commented
@aalyando а нащо? У тебе ж цей PR вже з апрувом

2023-09-25 16:31 UTC, aalyando commented
Просто закинуть в новый PR получается?

2023-09-25 20:13 UTC, merged